name: Release

env:
  APP_NAME: "DeathrunManager"
  BASE_MODULE_PROJECT_PATH: "src/DeathrunManager/DeathrunManager.csproj"
  SHARED_PROJECT_PATH: "src/DeathrunManager.Shared/DeathrunManager.Shared.csproj"
  
  BASE_MODULE_OUTPUT_PATH: "game/sharp/modules/Deathrun.Manager"
  SHARED_OUTPUT_PATH: "game/sharp/shared/DeathrunManager.Shared"
  
  DOTNET_VERSION: '10.0.x'
  CONFIGURATION: Release

on:
  push:
    if: startsWith(github.event.head_commit.message, 'push module')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for creating releases
      packages: write  # Required for publishing to GitHub Packages
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Get commit message
        id: commit
        run: |
          COMMIT=$(git log -1 --pretty=%B)

          {
            echo "commit_message<<EOF"
            echo "$COMMIT"
            echo "EOF"
          } >> $GITHUB_OUTPUT
          
          echo "Commit message:"
          echo "$COMMIT"
      
      # Versioning
      - name: Versioning
        id: build_version
        run: |
          VERSION=$(grep -oP '<Version>\K[^<]+' ./src/Directory.Build.props)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          IFS='.' read -r major minor patch <<< "$VERSION"

          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor_version=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT

          echo "commit_hash_short=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: dotnet restore

      # Build
      - name: Compile Module
        run: |
          dotnet publish $BASE_MODULE_PROJECT_PATH -c $CONFIGURATION --no-restore -o $BASE_MODULE_OUTPUT_PATH \
          -p:Version=${{ steps.build_version.outputs.version }} \
          -p:InformationalVersion=${{ steps.build_version.outputs.commit_hash_short }}

          dotnet publish $SHARED_PROJECT_PATH -c $CONFIGURATION --no-restore -o $SHARED_OUTPUT_PATH \
          -p:Version=${{ steps.build_version.outputs.version }} \
          -p:InformationalVersion=${{ steps.build_version.outputs.commit_hash_short }}

      # Assets
      - name: Copy assets
        run: |
          if [ -d .asset/game ]; then
            cp -r .asset/game/* game/sharp
          fi

      # Archives
      - name: Create archives
        run: |
          cd game
          tar -czf ../DeathrunManager${{ steps.build_version.outputs.version }}-build${{ github.run_number }}.tar.gz sharp/
          cd ..
          zip -r DeathrunManager${{ steps.build_version.outputs.version }}-build${{ github.run_number }}.zip game/sharp/

      # Artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: DeathrunManager${{ steps.build_version.outputs.version }}-build${{ github.run_number }}
          path: |
            game/sharp/modules/Deathrun.Manager/
            game/sharp/shared/DeathrunManager.Shared/

      # Changelog base (ONLY if minor >= 1)
      - name: Get changelog starting point
        if: ${{ steps.build_version.outputs.minor_version >= 1 }}
        id: changelog_starting_point
        run: |
          VERSION=${{ steps.build_version.outputs.version }}
          IFS='.' read -r major minor patch <<< "$VERSION"

          PREV_MINOR="$major.$((minor - 1)).$patch"

          git fetch --tags

          LOWEST=$(git tag | \
            grep -E "^${PREV_MINOR}build[0-9]+$" | \
            sed -E 's/.*build([0-9]+)/\1/' | \
            sort -n | \
            head -n 1)

          echo "full=${PREV_MINOR}build${LOWEST}" >> $GITHUB_OUTPUT

      # Build changelog
      - name: Build changelog
        id: changelog
        run: |
          MINOR_VERSION=${{ steps.build_version.outputs.minor_version }}
          
          if [ "$MINOR_VERSION" -gt 0 ]; then
            echo "body=Changelog: https://github.com/aquevadis/ms-cs2deathrun-public/compare/${{ steps.changelog_starting_point.outputs.full }}...${{ steps.build_version.outputs.version }}build${{ github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "body=" >> $GITHUB_OUTPUT
          fi

      # Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('{0}build{1}', steps.build_version.outputs.version, github.run_number) }}
          name: ${{ format('{0}build{1}', steps.build_version.outputs.version, github.run_number) }}
          files: |
            DeathrunManager${{ steps.build_version.outputs.version }}-build${{ github.run_number }}.tar.gz
            DeathrunManager${{ steps.build_version.outputs.version }}-build${{ github.run_number }}.zip
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
          make_latest: true

      # NuGet
      - name: Build and publish Nuget package
        if: startsWith(github.event.head_commit.message, 'push module + api v')
        run: |
          dotnet pack src/DeathrunManager.Shared/DeathrunManager.Shared.csproj --configuration Release --output .build/nuget
          dotnet nuget push .build/nuget/DeathrunManager.Shared.${{ steps.build_version.outputs.version }}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
          
  